networks:
  internal:
    driver: bridge
    internal: true
  external:
    driver: bridge

volumes:
  redis_data: {}

services:
  vk2tg:
    build:
      context: ../../..
      dockerfile: ./build/vk2tg/Dockerfile
    env_file:
      - "local.env"
    environment:
      - V2T_REDIS_ADDR=redis:6379
    ports:
      - "8420:8420"
    networks:
      - external
      - internal
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: "redis:alpine"
    networks:
      - internal
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
    deploy:
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - redis_data:/data
