apiVersion: apps/v1
kind: Deployment
metadata:
  name: vk2tg
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vk2tg
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vk2tg
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: vk2tg
        image: ghcr.io/lexfrei/vk2tg:latest
        imagePullPolicy: IfNotPresent
        name: vk2tg
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
---
apiVersion: v1
kind: Secret
metadata:
  name: vk2tg
  namespace: default
data:
  V2T_TG_TOKEN: XXX
  V2T_TG_USER: XXX
  V2T_VK_TOKEN: XXX
type: Opaque