apiVersion: apps/v1
kind: Deployment
metadata:
  name: vk2tg
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vk2tg
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vk2tg
    spec:
      containers:
        - name: vk2tg
          image: ghcr.io/lexfrei/vk2tg:latest
          envFrom:
            - secretRef:
                name: vk2tg
          env:
            - name: V2T_REDIS_ADDR
              value: "localhost:6379"
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
            capabilities:
              drop:
                - all
            readOnlyRootFilesystem: true
        - name: redis
          image: redis
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
          volumeMounts:
            - name: redis-pv
              mountPath: /data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
spec:
  storageClassName: longhorn-main
  capacity:
    storage: 128Mi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: Secret
metadata:
  name: vk2tg
  namespace: default
data:
  V2T_TG_TOKEN: XXX
  V2T_TG_USER: XXX
  V2T_VK_TOKEN: XXX
type: Opaque
