name: Lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.17"
          check-latest: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.1.0
      - name: hadolint
        uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: build/vk2tg/Dockerfile
      - uses: snyk/actions/setup@master
      - name: Run Snyk to check for vulnerabilities
        run: snyk test --sarif-file-output=snyk.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif
