name: Lint

on:
  push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
      - name: hadolint
        uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: build/vk2tg/Dockerfile
