name: Build Container Image for vk2tg

on:
  push:
    paths:
      - "build/vk2tg/**"
      - "cmd/vk2tg/**"
      - "internal/pkg/vk2tg/**"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/vk2tg.yaml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        with:
          images: ghcr.io/lexfrei/vk2tg
          flavor: |
            latest=true
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0
        with:
          platforms: "arm64,amd64"

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
        with:
          endpoint: builders
          config-inline: |
            [registry."docker.io"]
              mirrors = ["mirror.gcr.io"]

      - name: Login to GitHub Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        if: github.ref == 'refs/heads/master'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        if: github.ref == 'refs/heads/master'
        with:
          push: true
          context: .
          file: ./build/vk2tg/Containerfile
          platforms: linux/arm64, linux/amd64
          tags: ${{ steps.docker_meta.outputs.tags }}

      - name: Build
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        if: github.ref == !'refs/heads/master'
        with:
          context: .
          file: ./build/vk2tg/Containerfile
          platforms: linux/arm64, linux/amd64
          tags: ${{ steps.docker_meta.outputs.tags }}
